### ISSUE TITLE
windows::Win32::UI::WindowsAndMessaging Consts section breaks after letter M 

### ISSUE THREAD

**Issue by JCBurnside** [microsoft/windows-docs-rs#7]
![image](https://user-images.githubusercontent.com/10678224/132066910-e67a3d80-3937-4229-9e00-b2c408a09a71.png)
not sure what else to say on this.  there is many links layered on that one line there. At [here](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/UI/WindowsAndMessaging/index.html)

**Comment by GuillaumeGomez** [comment]
I think the issue has been fixed (I don't see it anymore).

**Comment by JCBurnside** [comment]
it is very much still present for me.
![image](https://user-images.githubusercontent.com/10678224/132126506-22f12418-7f53-4b85-9694-623809d8b10f.png)
I am using Chrome version 93.0.4577.63

**Comment by GuillaumeGomez** [comment]
I think you just found a chrome bug because it works perfectly fine in firefox. The [w3c validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fmicrosoft.github.io%2Fwindows-docs-rs%2Fdoc%2Fbindings%2FWindows%2FWin32%2FUI%2FWindowsAndMessaging%2Findex.html) confirmed that the HTML is fine as well.

Please open an issue on chrome?

**Comment by JCBurnside** [comment]
I can reproduce on Edge too so I guess it is the chromium core.
